### ISSUE TITLE
Question: Can you customize the arrow icon with something else?

### ISSUE THREAD

**Issue by jcaiani** [DimitryDushkin/sliding-pane#1]

**Comment by DimitryDushkin** [comment]
Hello. Right now it's not possible, but can be simply added by introducing new propery which can be used in this line https://github.com/DimitryDushkin/sliding-pane/blob/master/src/index.js#L36

**Comment by jcaiani** [comment]
thanks so much!
i was also wondering how i get the sliding transitions when sliding the window on the page. currently, by default it just appears on the page with no sliding.



On Friday, August 11, 2017, 1:41:02 PM EDT, Dimitry <notifications@github.com> wrote:


Hello. Right now it's not possible, but can be simply added by introducing new propery which can be used in this line https://github.com/DimitryDushkin/sliding-pane/blob/master/src/index.js#L36

**Comment by jcaiani** [comment]
Thanks!
