### ISSUE TITLE
Arrow should point in direction of close

### ISSUE THREAD

**Issue by akoolenbourke** [DimitryDushkin/sliding-pane#13]
First, thanks for the component. I noticed however that if you expand from the right, the arrow still points left. It should really point right to indicate which direction it will close.

Even better would be being able to customise the icon used.

Thanks

**Comment by DimitryDushkin** [comment]
Hey! Yeah, looks like a bug. I'll try to fix it on this week, but PR is welcome!) Still you can fix it by yourself via CSS like
```css
.slide-pane__close {
    transform: rotate(180)
}
```

**Comment by MartinConde** [comment]
It would also be nice to be able to pass in a custom icon or any component that contains an svg or something.

**Comment by akoolenbourke** [comment]
Thanks for the reply. I would PR but I'm a JS newbie and have no idea how to edit and test someone's library. I might take a look though later if I get there.
