### ISSUE TITLE
Render html code in Pane Title

### ISSUE THREAD

**Issue by bharamgundea77** [DimitryDushkin/sliding-pane#16]
i want to render html code 
e.g. `<span className='badge badge-danger text-center> xyz </span>`
in place of simple text title how can i do that ?

**Comment by DimitryDushkin** [comment]
Hey. Just placing it in title will work like
```
<SlidingPane
                title={<span className='badge badge-danger text-center'> xyz </span}
....
```

**Comment by bharamgundea77** [comment]
Thank you so much for your prompt response. It's working fine
