### ISSUE TITLE
Nested Component Javascript not working

### ISSUE THREAD

**Issue by adimopoulos** [DimitryDushkin/sliding-pane#18]
I have a function I am calling in componentDidMount.  When I place the affected elements outside of the sliding pane component they are working fine.  When I place them inside, the javascript fails to execute.  Is this a bug, or something I am missing?

**Comment by spidgorny** [comment]
My situation is similar. I have a form inside the pane. onSubmit event is not working.
```
<form onSubmit={(e) => console.log(e)}>...</form>
```
