### ISSUE TITLE
This Screen Render issue

### ISSUE THREAD

**Issue by tamilk0212** [DimitryDushkin/sliding-pane#19]
App element is not defined. Please use `Modal.setAppElement(el)` or set `appElement={el}`. This is needed so screen readers don't see main content when modal is opened. It is not recommended, but you can opt-out by setting `ariaHideApp={false}`.

**Comment by tamilk0212** [comment]
In Microsoft Edge Browser

**Comment by WilfriedDeluche** [comment]
It would be nice to have a solution to get rid of this warning.
`SlidingPane` component does not support `ariaHideApp` property.
And it seems like `Modal.setAppElement(el)` with `el` being `body` or something else doesn't do anything.

**Comment by yuvraj88** [comment]
any proper solution for the above issue?

**Comment by MisterAJ** [comment]
Also experiencing this issue.

**Comment by DimitryDushkin** [comment]
Fixed.
