### ISSUE TITLE
Not sliding: I can open and close the slider, but there are not transitions.

### ISSUE THREAD

**Issue by jcaiani** [DimitryDushkin/sliding-pane#2]
Do i need to do something additional to get the animation?

**Comment by DimitryDushkin** [comment]
Did you `import 'react-sliding-pane/dist/react-sliding-pane.css';`?

**Comment by jcaiani** [comment]
Yes, I have the styling of the modal, but no animations.

**Comment by DimitryDushkin** [comment]
It's hard to tell. Is demo working for you https://dimitrydushkin.github.io/sliding-pane/example.html ? Here it's sources https://github.com/DimitryDushkin/sliding-pane/blob/master/docs/src/app.js You can build demo by yourself by 
```
// clone repo
npm i
npm run docs
open docs/example.html
```

**Comment by jcaiani** [comment]
The odd thing, is that when I slide in from the left, the animations exist. If I slide in from the right they usually do not exist but occasionally they do.

**Comment by jcaiani** [comment]
yes the demo works fine.

**Comment by DimitryDushkin** [comment]
I've release 2.0. Is it work for you now?

**Comment by DimitryDushkin** [comment]
Closing for now.
