### ISSUE TITLE
Unable to scroll the panel in Safari

### ISSUE THREAD

**Issue by celento** [DimitryDushkin/sliding-pane#20]
Scrolling the contents of the panel does not work in Safari.

Tested on version: 12.0.3

**Comment by DimitryDushkin** [comment]
Hey! Thank you for reporting. I'll hope I'll have time to investigate it. Did you find the cause of the bug?

**Comment by celento** [comment]
Unfortunately I haven't investigated it in detail. Found that the scrolling
works fine if I do a window resize. Hope that might help you out.

**Comment by slgriffiths** [comment]
That fix from Hiker-Hope doesn't appear to solve another underlying issue.  You can see this in the example demo.

Reduce your browser height to be smaller than the blue image (e.g. crop the image some). Then open the right side slider. You get the double scroll bars (at least in Chrome), but you cannot scroll with your mouse.

Some things that fix this in the moment:
1. Open inspector, and just change the scroll behavior from `auto` to `scroll` or the overflow-y to another value. You can now scroll.
2. Fire a window resize event and you can now scroll (or just manually adjust the size of your browser window slightly)

**Comment by moseskimfashionnova** [comment]
Does this work on most modern browsers?

**Comment by DimitryDushkin** [comment]
It's working on Safari now
