### ISSUE TITLE
Slide-in animation not working in macOS Safari, iOS Safari or iOS Chrome

### ISSUE THREAD

**Issue by kylefoundry** [DimitryDushkin/sliding-pane#21]
The slide-in animation works fine on macOS Chrome, but the sliding animation does not work on macOS Safari, iOS Safari, or iOS Chrome.

Slide-out animation always works across all browsers, as well as the fade in/out of the overlay on both appear and disappear.

**Comment by DimitryDushkin** [comment]
Hey! I cannot reproduce it. Do you see the problem on example page — https://dimitrydushkin.github.io/sliding-pane/example.html ?
