### ISSUE TITLE
WebpackError: ReferenceError: window is not defined

### ISSUE THREAD

**Issue by kieranstartup** [DimitryDushkin/sliding-pane#29]
Hey,

I'm using this with Gatsby and I just tried building my site on Netlify but I'm running into an issue where the window is not defined. Is there a workaround for this or anyway to make this SSR compatible? 

Here's the error that Netlify is throwing:

`WebpackError: ReferenceError: window is not defined
react-sliding-pane.js:1 Object../node_modules/react-sliding-pane/dist/react-sliding-pane.js
node_modules/react-sliding-pane/dist/react-sliding-pane.js:1:418`

Thanks!

**Comment by DimitryDushkin** [comment]
Please try 4.0.1. I've switched webpack to rollup for build, should help.
