### ISSUE TITLE
 Cannot use import statement outside a module

### ISSUE THREAD

**Issue by rewrite123** [DimitryDushkin/sliding-pane#38]
If you are using server side rendering, you might run into the following

```
...\node_modules\react-sliding-pane\dist\react-sliding-pane.js:1
import React from 'react';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

to solve, in your babel config edit it to

`require("@babel/register")({
  ignore: [
//    /(node_module)/ //This right here! Now it will throw babel error, but it will not crash server
  ],`

Probably a way to solve this issue using babel to compile react-sliding-pane so that it will not throw this error when running.

**Comment by regarde** [comment]
I am getting the same error while using the module with Meteor. Unfortunately, their Babel wrapper does not support babelrc ignore.

How could I compile react-sliding-pane to make it work?

Thanks for your help!

**Comment by ayxos** [comment]
I have the same problem. I rolled back to 3.0.1

**Comment by heenasangtani** [comment]
any solution yet?

**Comment by kdog1425** [comment]
Getting same error, with create-react-app (ejected and non ejected), and jest. So far have not found a working solution.

**Comment by kdog1425** [comment]
ok found a solution, if this helps anyone. In our package.json, under "jest", config such that react-sliding-pane is not ignored.
````
"transformIgnorePatterns": [
      "[/\\\\]node_modules[/\\\\](?!react-sliding-pane).+\\.(js|jsx)$",
      "^.+\\.module\\.(css|sass|scss)$"
    ],
````

**Comment by DimitryDushkin** [comment]
That is because package is not providing  CommonJS exports. I'll fix it.

**Comment by DimitryDushkin** [comment]
Made 5.0 release https://www.npmjs.com/package/react-sliding-pane please try. It worked for me within CRA.

**Comment by DimitryDushkin** [comment]
Closing. Please re-open if issue will occur again.
