### ISSUE TITLE
On panel close page scroll to top

### ISSUE THREAD

**Issue by rb162215** [DimitryDushkin/sliding-pane#42]
I am using sliding pane and i love it.
However i am getting one issue while using pane in list item click.

I have a long list to display on clicking of a list item Sliding pane is open, issue is when some one scroll list and on 4th item click sliding pane is open then after closing pan list scroll to 0 index.

**Comment by DimitryDushkin** [comment]
Hello!  It's hard to help you without example. Could you please provide some using Codesandbox or StackBlitz?
