### ISSUE TITLE
No Animation on Mobile Devices

### ISSUE THREAD

**Issue by Ciddarth-raaj** [DimitryDushkin/sliding-pane#45]
Im using iPhone X to test and there is slide in animation while opening, but it works fine while closing it. The animation works properly in desktop (MacBook Air 2017).

**Comment by dagreatbrendino** [comment]
Bump. Experiencing the same thing on safari 14+. Slide out animation works fine but slide in animation does not.

**Comment by johnfranztaguranRC** [comment]
Im testing if this works at mobile devices, it does but the styling seems not.

**Comment by dagreatbrendino** [comment]
bump, seems not to work on safari for both desktop and mobile

**Comment by richessler** [comment]
Bump, just tried today and used your example page https://dimitrydushkin.github.io/sliding-pane/example.html to test on google chrome on iphone 11Pro. it just jerks open and jerks close, bad experience.

**Comment by DimitryDushkin** [comment]
Checkout v 7.0. Should be fixed. Report if it is not. Thanks!

**Comment by dagreatbrendino** [comment]
Seems to be working now. Thanks!
