### ISSUE TITLE
How can I fit jsx on the title?

### ISSUE THREAD

**Issue by tonyjara** [DimitryDushkin/sliding-pane#46]
Hi, i'm already using jsx in the title and it works. But I get a warning.
How can I remove that warning? 
![Screenshot 2020-10-07 213159](https://user-images.githubusercontent.com/45184825/95401800-8e6ce900-08e4-11eb-8bac-936e667f2e5c.png)

**Comment by DimitryDushkin** [comment]
Hey! Oh. looks like auto-generated PropTypes for title is not accurate. This like should be fixed and rebuild all the things. I'll try to fix it today.

**Comment by DimitryDushkin** [comment]
Fixed in 6.1.1.
