### ISSUE TITLE
Visible tab head to expand panel

### ISSUE THREAD

**Issue by sunviwo** [DimitryDushkin/sliding-pane#48]
Hi, I love this component. The missing feature for my use case is that I'd like to have a kind of tab head with a label on which a user can click and expand the panel. The tab can be positioned on the left, the bottom or the right depending on the side the panel is sliding from and still be visible next to the expanded panel and serve as closing button too. Would be really cool such a feature.
Ok I'd love to have a from top pane too. Thanks in advance.

**Comment by DimitryDushkin** [comment]
Hey! I'm not using this component anymore, so I'm only supporting it.
