### ISSUE TITLE
How we can disable overlay from slide?

### ISSUE THREAD

**Issue by imdhiru** [DimitryDushkin/sliding-pane#49]

**Comment by DimitryDushkin** [comment]
Hey! Do you want still have functionality of closing pane via overlay click?

**Comment by imdhiru** [comment]
> Hey! Do you want still have functionality of closing pane via overlay click?

no, just wants to close the panel on button click only

**Comment by DimitryDushkin** [comment]
You can add style like
```
.slide-pane__overlay {
  pointer-events: none;
}
```
