### ISSUE TITLE
How to automatically change width ?

### ISSUE THREAD

**Issue by amit-carsales** [DimitryDushkin/sliding-pane#55]
How to automatically change width based on screen size. currently, I am using 80% but I want to change it to 100% for mobile view. For other tasks, till now I was using the @media screen, but that doesn't work here as I need to pass a string. Please provide a solution and if possible with an example. Thanks!

**Comment by blackandblue302** [comment]
width={window.innerWidth > 620 ? "20%" : "100%"}
