### ISSUE TITLE
Include the css in the bundle

### ISSUE THREAD

**Issue by DrGor** [DimitryDushkin/sliding-pane#57]
First of all thank you for the library.

Usually, if you are sure that your average user won't need to override your styles, then the styles can be a part of the bundle.
For this project, the css names are tightly coupled with the implementation.
Is there a specific reason why the average user must import the css manually?

**Comment by DimitryDushkin** [comment]
Hey! You're absolutely right.
I've done it in such a way just because it was the simplest way to do it back then when I first opened this solution. Nowadays, I prefer CSS-in-JS or CSS modules.
