### ISSUE TITLE
Close panel from within panel

### ISSUE THREAD

**Issue by SimonMerrikin** [DimitryDushkin/sliding-pane#65]
Is there a way to close the sliding panel from inside the panel?

**Comment by DimitryDushkin** [comment]
Hey! Yeah, you can add something inside content which will trigger update of `isOpen` property of the component

**Comment by alexpapworth** [comment]
Ah, this doesn't seem to trigger `onRequestClose`. Any way we can get that code to execute as well?

**Comment by alexpapworth** [comment]
Ah, don't worry. We can just call what as in `onRequestClose` in the function we created to handle closing the panel!

It's all clicking now 😁

**Comment by DimitryDushkin** [comment]
Cool :)
