### ISSUE TITLE
React 18 not supported?

### ISSUE THREAD

**Issue by spidgorny** [DimitryDushkin/sliding-pane#73]
Stopped working with React 18. Maybe they implement portals differently now.
I can see the divs and classes in the inspector, but they are completely invisible.
Tested with react: <18.0.0 and it works again.

```
  System:
    OS: Windows 10 10.0.19044
    Memory: 12.86 GB / 31.75 GB
  Binaries:
    Node: 16.5.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.4.1 - C:\Program Files\nodejs\npm.CMD
  Managers:
    pip3: 21.2.4 - C:\Python39\Scripts\pip3.EXE
    RubyGems: 3.2.22 - C:\tools\ruby30\bin\gem.CMD
  Utilities:
    CMake: 3.22.0 - /c/Program Files/CMake/bin/cmake
    Git: 2.32.0. - /mingw64/bin/git
  Virtualization:
    Docker: 20.10.11 - C:\Program Files\Docker\Docker\resources\bin\docker.EXE
  IDEs:
    VSCode: 1.66.1 - C:\Program Files\Microsoft VS Code\bin\code.CMD
    Visual Studio: 17.0.32014.148 (Visual Studio Community 2022)
  Languages:
    Bash: 4.4.23 - C:\Program Files\Git\usr\bin\bash.EXE
    Perl: 5.32.1 - C:\Program Files\Git\usr\bin\perl.EXE
    PHP: 7.4.21 - C:\tools\php74\php.EXE
    Python: 3.9.6 - /c/Python39/python
    Ruby: 3.0.2 - C:\tools\ruby30\bin\ruby.EXE
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (100.0.1185.39)
    Internet Explorer: 11.0.19041.1566
```

**Comment by undermuz** [comment]
i've faced this problem.

i guess it is because of it:
![image](https://user-images.githubusercontent.com/6875507/183772762-7818569c-8e82-4775-84c1-61516e307f78.png)
![image](https://user-images.githubusercontent.com/6875507/183772823-f7c9c867-74aa-4879-8e6e-911b6f6b6190.png)

**Comment by undermuz** [comment]
Because React re-run effects to check for restorable state

![image](https://user-images.githubusercontent.com/6875507/183773005-afbe93e4-eb69-4387-9715-ce521d90810b.png)

**Comment by DimitryDushkin** [comment]
7.2.0 released with the fix. Thanks @spidgorny and @undermuz for report and fix 🙏
