### ISSUE TITLE
React Native Version of sliding pane

### ISSUE THREAD

**Issue by esegebart** [DimitryDushkin/sliding-pane#78]
I am just curious if you will make this for React Native too? 

After searching and searching for a React Native sliding panel that would pop out from the right since you cannot style a Modal in react native, I found this and it's exactly what I wanted! But its for react. 

If you will be making this for React Native too, please let me know!

**Comment by DimitryDushkin** [comment]
Hey @esegebart! Well, the nature of my work is a bit different, so I'm cannot tell that RN version will be released anytime soon. 
I'll keep in mind your request though.
