### ISSUE TITLE
Incorrect peer dependency (2.0.1 v)

### ISSUE THREAD

**Issue by gcardacci** [DimitryDushkin/sliding-pane#8]
Hello Dimitry, thanks for this useful component!
I'm using the latest version (2.0.1) of the library and I'm getting the following warnings every time I run yarn on my project:

> warning " > react-sliding-pane@2.0.1" has incorrect peer dependency "react@^15.0.0".
> warning " > react-sliding-pane@2.0.1" has incorrect peer dependency "react-dom@^15.0.0".

Maybe you have to update these dependencies.

**Comment by DimitryDushkin** [comment]
Hey, glad it helps.
What's your react version in package.json?

**Comment by gcardacci** [comment]
@DimitryDushkin My version of React is the latest available. (16.2.0)

**Comment by shri-msk-2018-reviewer** [comment]
Done, enjoy 2.0.2 =)

**Comment by DimitryDushkin** [comment]
Done, enjoy 2.0.2 =)
