### ISSUE TITLE
A bit confused about applying styles

### ISSUE THREAD

**Issue by fhgaha** [DimitryDushkin/sliding-pane#83]
To make sliding work like in the example on pressing button "Open right pane" I had to namually copy-paste this styles https://github.com/DimitryDushkin/sliding-pane/blob/master/src/react-sliding-pane.css into my project css file. Is it supposed to be like that?

**Comment by DimitryDushkin** [comment]
Hey! Kind of. Instead you can directly import them (see example in readme):
import "react-sliding-pane/dist/react-sliding-pane.css";

**Comment by fhgaha** [comment]
Oh I see. Thank you!
