### ISSUE TITLE
Navigating Through Tabs on Form Element in Sliding Pane Not working in Chrome

### ISSUE THREAD

**Issue by born-curious** [DimitryDushkin/sliding-pane#9]
Hi,
I have used sliding pane in my code. Everything seems to work nicely except that I can't navigate through tab on Form Elements which I have kept in Sliding Pane. The problem only occurs in Chrome. In Firefox it behaves as it should. 

I have also tried the same code on other computers. There is same issue with Chrome there too.

**Comment by phayman** [comment]
Was there a resolution for this? I'm also having this issue
